[pytest]
# -------------------------------------------------------------------
# Test discovery paths
# -------------------------------------------------------------------
testpaths =
    tests
    steps_definition

python_files =
    test_*.py
    steps_*.py

# -------------------------------------------------------------------
# Pytest markers (important for organizing tests)
# -------------------------------------------------------------------
markers =
    ui: Tests that require Playwright browser
    smoke: Quick smoke tests
    regression: Regression Tests
    home: Home page tests
    services: Services page tests
    portfolio: Portfolio tests
    partners: Partners tests
    solutions: Solutions page tests
    insights: Insights tests
    careers: Careers tests
    about: About page tests
    contact_us: Contact Us page tests

    api: API-only tests (no browser)
    api_get_record: Get Record API Test
    api_create_record: Create Record API Test
    api_update_record: Update Record API Test
    api_delete_record: Delete Record API Test

# -------------------------------------------------------------------
# Pytest options
# -------------------------------------------------------------------
addopts =
    -v
    -s
    --html=report.html
    --self-contained-html
    -n 1
    --dist=loadscope

# -------------------------------------------------------------------
# Enable CLI logging (so logger.info appears during test)
# -------------------------------------------------------------------
log_cli = false
log_cli_level = CRITICAL
log_cli_format = %(asctime)s | %(levelname)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

# -------------------------------------------------------------------
# Pytest-BDD: Display Feature, Scenario, and Step names
# -------------------------------------------------------------------
bdd_features_base_dir = features

bdd_feature_format = "{feature}"
bdd_scenario_format = "{scenario}"
bdd_step_format = "{keyword} {step_name}"

# -------------------------------------------------------------------
# Ignore noisy warnings
# -------------------------------------------------------------------
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning